version: 1.0.{build}

branches:
  only:
  - master

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.3.9.1
  - choco install maven -version %MAVEN_VERSION%
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - set PATH=%JAVA_HOME%\bin;%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin

build_script:
  - ps: ./appveyor.ps1
