# Generated by Django 3.1 on 2020-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20200814_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='is_open',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Closed')], default=0),
        ),
    ]
