# Generated by Django 3.0.2 on 2020-03-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20200227_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridge',
            old_name='adresse',
            new_name='address',
        ),
    ]
