# Generated by Django 3.0.4 on 2020-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20200602_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='city',
            field=models.CharField(default='city', max_length=45),
            preserve_default=False,
        ),
    ]
