# Generated by Django 3.0.2 on 2020-03-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20200317_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
        migrations.RenameModel(
            old_name='SpecialDays',
            new_name='SpecialDay',
        ),
    ]
