# Generated by Django 3.1 on 2020-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_fridgecontentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
