# Generated by Django 3.0.7 on 2020-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_fridge_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default.JPG', upload_to='images/'),
        ),
    ]
