# Generated by Django 3.1 on 2020-09-02 09:19

from django.db import migrations, models
import fridge.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_auto_20200830_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='latitude',
            field=models.FloatField(blank=True, validators=[fridge.validators.latitude_longitude_validators]),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='longitude',
            field=models.FloatField(blank=True, validators=[fridge.validators.latitude_longitude_validators]),
        ),
    ]
