# Generated by Django 3.0.2 on 2020-03-26 15:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_auto_20200325_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialday',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='holiday_date',
        ),
        migrations.AddField(
            model_name='specialday',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 16, 35, 25, 519115)),
        ),
        migrations.AddField(
            model_name='specialday',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
