# Generated by Django 3.0.5 on 2020-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_fridgefollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
