# Generated by Django 3.0.7 on 2020-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_fridge_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridge',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
