# Generated by Django 3.0.8 on 2020-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0010_reportcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='bio',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='gluten_free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='halal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='lactose_free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
