# Generated by Django 3.0.4 on 2020-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0011_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
