# Generated by Django 3.0.8 on 2020-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0011_auto_20200708_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='images/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
