# Generated by Django 3.0.8 on 2020-07-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0012_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=45)),
                ('product_number', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('visa', models.CharField(max_length=45)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge')),
            ],
        ),
    ]
