# Generated by Django 3.0.4 on 2020-04-25 08:54

import django.core.validators
from django.db import migrations, models
import fridge.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0013_auto_20200420_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(validators=[fridge.validators.expiration_date_validator]),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='NPA',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^\\d{4}$', "Ce NPA n'est pas valide")]),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='image',
            field=models.ImageField(default='images/store-default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(\\+41|0)\\d{9}$', "Ce numéro de téléphone n'est pas valide")]),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='from_hour',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='to_hour',
            field=models.DateField(),
        ),
    ]
