# Generated by Django 3.0.8 on 2020-07-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0014_temperaturecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
