# Generated by Django 3.0.4 on 2020-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0014_auto_20200425_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='from_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='to_hour',
            field=models.TimeField(),
        ),
    ]
