# Generated by Django 3.0.8 on 2020-07-13 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0016_auto_20200713_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialday',
            name='description',
            field=models.CharField(default='Holiday', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialday',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
