# Generated by Django 3.0.8 on 2020-07-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0017_auto_20200713_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridge',
            old_name='NPA',
            new_name='zip_code',
        ),
    ]
