# Generated by Django 3.0.8 on 2020-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0018_auto_20200713_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
    ]
