# Generated by Django 3.0.8 on 2020-07-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0020_auto_20200719_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temperaturecontrol',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
