# Generated by Django 3.0.8 on 2020-07-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0021_auto_20200722_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporting',
        ),
    ]
