# Generated by Django 3.1 on 2020-08-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0022_delete_reporting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
