language: python
rvm:
 - 3.7
 - python
services:
  - mysql
env:
  - DJANGO=3.0 DB=mysql
addons:
  sonarcloud:
    organization: "gaelchriste"
    token:
      secure: "5ZnWjcRKOfiXJUDTfl8Zvy/J+0f9ujvq5j5o+Dk5OS8S6CvBsd1iGSFHujFG2yMVv/wleK20Gvx2BWeGq99FfKgS1S2ej2S4ULJzoycgKuAH/zCPsTO2F+4Pj4/kt+YSsT5YPCIh6SdG8Qq+i1r77pB+WDiJ59UKsZ98ZVDZJ0nYsd/hUr8j0pCHqSl0pZel5NVeICMs32LQ+C1VMsLFB32koGxpPlIVLdFesIRfxQfiGnrdd/I9gAZWoqb6RbmgiFO2DOezBNFphdmAX24XwnhAE8hYMTcegDzkPHYlFis/ND48X+AXuT8Td2KVWHtG6nGDLlvguzjdP3nXKYx6xqY3cps/MlE8wE22rAXNr1P3Or8m+bUjMlz6FJE6iJuIwy8+hBIqzesniNjNizDUJk1P1s0klLpHb4sX62rlC4yYnzGaVIIB69TaUI9k3/wCDWB2WLVnZIYVH8m2IWnHNmVFM8ozGoJONZaI9BRO0OY/znp9dtCotM/qXTLkn3A/gi4WMEBaX9lLP5UL+RryjU0Lfq3Ux2k6K6jzQNQTzMKHRkZ6ElLsiONEDOaJi+tvLruPR2g6HHkMHQz/CmQJxYKO8lFCmqmbqolKHrsIZdevJvhg5fEVcTpC3kd9sp9rwkx1rbHIiC1eoChmZ7VwJ3uHORRXBV2M1e+skERlaQA="
before_install:
  - export DJANGO_SETTINGS_MODULE=freego.settings.production_settings

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install mysqlclient
before_script:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - python manage.py migrate
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source='.' manage.py test
  - coverage xml -i
  - sonar-scanner
after_success:
  - coveralls

  