# Generated by Django 3.0.3 on 2020-02-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('adresse', models.CharField(max_length=45)),
                ('NPA', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('fridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.User')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.User'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('vegetarian', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('expiration_date', models.DateTimeField()),
                ('fridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.User')),
            ],
        ),
    ]
