# Generated by Django 3.0.3 on 2020-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
