# Generated by Django 3.0.2 on 2020-03-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_auto_20200317_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='special_days',
        ),
        migrations.AddField(
            model_name='openinghour',
            name='fridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge'),
        ),
        migrations.AddField(
            model_name='specialday',
            name='fridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge'),
        ),
    ]
