# Generated by Django 3.0.2 on 2020-03-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_auto_20200326_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 16, 36, 14, 977727)),
        ),
    ]
