# Generated by Django 3.0.2 on 2020-03-26 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_auto_20200326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialday',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
